### ISSUE TITLE
Error on installing modules from ZIP

### ISSUE THREAD

**Issue by PDiracDelta** [genepattern/genepattern-server#82]
UPDATE: the same happens when the install script requires Python3(.6).

Whenever I try to install a module from ZIP, I get an error about a substitution for \<perl\>:

> Errors:1.GtfToBed: no substitution available for \<perl\> in command line \<perl\> \<libdir\>gtf2bed.pl \<GTF.file\>.

This is not only for the GtfToBed module. `perl` _is_ installed on the system:
```
$ which perl
/usr/bin/perl
```

Additional remark: the _actual_ error message hasn't been properly HTML-decoded when displayed by GenePattern:

> Errors:1.GtfToBed: no substitution available for \&lt;perl\&gt; in command line \&lt;perl\&gt; \&lt;libdir\&gt;gtf2bed.pl \&lt;GTF.file\&gt;.

**Comment by bahill** [comment]
Hello, 

Apologies for the late reply, we haven't been in the habit of monitoring GitHub issues. Instead, we regularly monitor our [public forum](https://groups.google.com/forum/#!forum/genepattern-help).

The first bit of information we will need is what platform you are running on - Mac or Linux? and which version of GenePattern did you install?

Best
-Barbara

**Comment by PDiracDelta** [comment]
OK @bahill , thanks for your reply. Someone else is working on this project now, and I have notified them. Let's hope they pick up the issue on your forum. I can tell you that the OS is Ubuntu 18.04.

**Comment by bahill** [comment]
This is now being handled in our forum:  https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/genepattern-help/JMFnFObpoLA/qx6WqCWmBQAJ
