### ISSUE TITLE
For help, see https://groups.google.com/g/genepattern-help

### ISSUE THREAD

**Issue by liefeld** [genepattern/genepattern-server#90]
Please use our Google group to get help with this project

https://groups.google.com/g/genepattern-help

**Comment by vdtoorn** [comment]
That page does not exist, according to Google?

**Comment by liefeld** [comment]
vdtoorn, that link is working for me.  What do you see when you click on it?

**Comment by liefeld** [comment]
Hi
seems that some people can see this link and others cannot on our team.  Try to use this link instead.

https://groups.google.com/forum/#!forum/genepattern-help

Can you tell me what page/site you found that broken link on?

Thanks

Ted

**Comment by liefeld** [comment]
never mind about the question, I see I sent it out here a few months ago
